version: '3'

services:
#MANDATORY##########################################################
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ${VOLUME_ROOT}/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - ${VOLUME_ROOT}/wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - docker-network
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - ${VOLUME_ROOT}/mariadb:/var/lib/mysql
    networks:
      - docker-network
    restart: unless-stopped
#BONUS##########################################################
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    networks:
      - docker-network
    restart: unless-stopped
    ports:
      - "8080:80"
  website:
    build: ./requirements/bonus/website
    container_name: website
    networks:
      - docker-network
    restart: unless-stopped
    ports:
      - "8081:80"
  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    networks:
      - docker-network
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    volumes:
      - ${VOLUME_ROOT}/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: unless-stopped
networks:
  docker-network:
    driver: bridge